<?php
// $Id$
/**
 * @file
 * modify users authentication source via VBO
 *
 */


/**
 * Implements hook_user_operations().
 */
function user_authentication_source_user_operations() {
  $operations = array(
    'export_saml' => array(
      'label' => t('Let user authenticate with SimpleSAML'),
      'callback' => 'user_authentication_source_claim_user_saml',
    ),
    'export' => array(
      'label' => t('Let user authenticate with CUWebAuth'),
      'callback' => 'user_authentication_source_claim_user',
    ),
  );
  return $operations;
}

/**
 * Mark the user for CUWebAuth authentication
 * @param array $accounts
 */
function user_authentication_source_claim_user($users, $view) {
  // see http://api.drupal.org/api/drupal/modules--user--user.module/function/user_external_login_register/6
  $module = 'cuwebauth';
  foreach ($users as $uid) {
    // TODO Convert "user_load" to "user_load_multiple" if "$uid" is other than a uid.
    // To return a single user object, wrap "user_load_multiple" with "array_shift" or equivalent.
    // Example: array_shift(user_load_multiple(array(), $uid))
    $auser = user_load($uid);
    $userinfo = array(
      "authname_$module" => $auser->name,
      );
    $account = user_save($auser, $userinfo);
  }
}

/**
 * Mark the user for SimpleSAML authentication
 * @param array $accounts
 */
function user_authentication_source_claim_user_saml($users, $view) {
  // see http://api.drupal.org/api/drupal/modules--user--user.module/function/user_external_login_register/6
  $module = 'simplesamlphp_auth';
  foreach ($users as $uid) {
    // TODO Convert "user_load" to "user_load_multiple" if "$uid" is other than a uid.
    // To return a single user object, wrap "user_load_multiple" with "array_shift" or equivalent.
    // Example: array_shift(user_load_multiple(array(), $uid))
    $auser = user_load($uid);
    $userinfo = array(
      "authname_$module" => $auser->name,
      );
    $account = user_save($auser, $userinfo);
  }
}
